# Generated by Django 2.2 on 2019-04-26 05:21

from django.db import migrations, models
import stdimage.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Intro',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ijudul', models.CharField(max_length=50)),
                ('iisi', models.TextField(blank=True)),
                ('ifoto', stdimage.models.StdImageField(blank=True, null=True, upload_to='home/static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Services',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sjudul', models.CharField(max_length=50)),
                ('sisi', models.TextField(blank=True)),
                ('sfoto', stdimage.models.StdImageField(blank=True, null=True, upload_to='home/static/images/')),
            ],
        ),
        migrations.CreateModel(
            name='Testi',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tnama', models.CharField(max_length=30)),
                ('tisi', models.TextField(max_length=600)),
            ],
        ),
        migrations.CreateModel(
            name='Works',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('wfoto', stdimage.models.StdImageField(blank=True, null=True, upload_to='home/static/images/')),
            ],
        ),
    ]
